SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT 1 FROM SysObjects WHERE Name = 'GameTags')
BEGIN
	--* drop table dbo.GameTags
	RETURN
END

CREATE TABLE dbo.GameTags
(
    GameId int NOT NULL,
    TagId int NOT NULL
) ON [PRIMARY]

ALTER TABLE dbo.GameTags ADD CONSTRAINT PK_GameTags PRIMARY KEY CLUSTERED
(
    GameId ASC,
    TagId ASC
)
WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    SORT_IN_TEMPDB = OFF,
    IGNORE_DUP_KEY = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]

ALTER TABLE dbo.GameTags ADD CONSTRAINT FK_GameTags_Games FOREIGN KEY (GameId)
REFERENCES dbo.Games(Id)
ON DELETE CASCADE

ALTER TABLE dbo.GameTags ADD CONSTRAINT FK_GameTags_Tags FOREIGN KEY (TagId)
REFERENCES dbo.Tags(Id)
ON DELETE CASCADE